### ISSUE TITLE
这个字体有点少见，能不能出一期支持overleaf的版本的

### ISSUE THREAD

**Issue by Musicminion** [myhsia/litetable#1]
感谢这个project的作者，课表也真的很好看，可惜在overleaf编译不太能实现，因为缺乏相关的字体，如果能考虑一下支持overleaf版本的会更好捏（

参考链接：https://cn.overleaf.com/learn/latex/Questions/Which_OTF_or_TTF_fonts_are_supported_via_fontspec%3F#Chinese

作者辛苦啦~ 新年快乐！

**Comment by myhsia** [comment]
这个字体可以根据个人喜好更改哈，我本人比较喜欢香港的异体字（繁体字），所以特意在 cls 中对粗体使用了 Chrion Sung HK
字体，昭源宋体），可以下载 cls后删掉那段 setCJK 命令，但是保留使用 xeCJK或ctex宏包的命令， 就会变成默认的宋体啦～
后期会开放出直接在文档中自定义字体的接口，感谢您的建议，敬请期待～

**Comment by myhsia** [comment]
目前最新版本情况是，Overleaf 暂不支持（并不是字体原因），因为目前 Overleaf 中 expl3 的版本问题，暂不支持在 Overleaf 编译（因为 Overleaf 的expl3版本不支持 e-type 变量，就不能用\clist_count:e），当然你可以自行导入最新版宏包。。。不过最好还是本地吧，直接 sudo tlmgr 升级下

**Comment by myhsia** [comment]
字体的话，最新版本我在 demo 文件中写了两行注释掉的 CJK 命令，可以通过这个自己设置字体，我写的是 Chiron Sung HK，你可以设置电脑里有的字体作为“黑体”

**Comment by xiamyphys** [comment]
New Version 3.0a has been pre-released. In this version

**Comment by myhsia** [comment]
New Version 3.0a has been pre-released.

- This version is mostly rewritten in LaTeX3, and the `course` command is changed into `keyval` style.

- This version supports pdflatex compiler, and users can choose font freely.

- This version has been optimized for the course with the height of only one unit.

- Manuals for this version have not completed till now, they will be completed on 22, Sep. The user manual will be presented in three languages: English (`texdoc litetable-en`), Chinese (`texdoc litetable-cn`), and Cantonese (`texdoc litetable-hk`).

--- 

新版本 3.0a 已经预发布.

- 此版本大部分由LaTeX3重写，`course`命令现已更改为`keyval`样式.

- 此版本支持 pdflatex 编译，用户可自由选择字体.

- 此版本针对高度只有一个单位的课程块优化.

- 用户手册将于9月22日完成，目前暂未完成. 用户手册将以三种语言呈现：英文 (`texdoc litetable-en`)，中文 (`texdoc litetable-cn`)，和粤语 (`texdoc litetable-hk`).

--- 

新版本3.0a已經預發佈.

- 此版本部分由LaTeX3重寫，`course`命令現已更改為`keyval`款式.

- 此版本支持pdflatex編譯，用戶可自由選擇字體.

- 此版本針對高度淨系得個單位嘅課程蚊優化.

- 用戶手冊放將於9月22日完成，宜家暫未完成. 用戶手冊放將以三種語言呈現：英文（`texdoclitetable-en`），中文（`texdoclitetable-cn`），同粵語（`texdoclitetable-46540513`）.

**Comment by myhsia** [comment]
Overleaf现已支持TeXLive 2024，故可在Overleaf上顺利编译. 但由于expl3的缘故，此模板目前暂不支持低于TeXLive 2024的版本.
